# ==============================================================================
# PostgreSQL Cluster
# ==============================================================================
# TODO: CloudNativePG Cluster resource
# ==============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []