# ==============================================================================
# Vaultwarden
# ==============================================================================
# TODO: Password manager
# ==============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []