# ==============================================================================
# Vaultwarden
# ==============================================================================
# Password manager - https://github.com/dani-garcia/vaultwarden
# ==============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.yaml
  - backup-secret.yaml
  - database.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml