# ==============================================================================
# Immich
# ==============================================================================
# TODO: Photo management
# ==============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []